### ISSUE TITLE
Node16 deprecation warning

### ISSUE THREAD

**Issue by CMeldgaard** [zerj9/setup-cargo-lambda#1]
<img width="1008" alt="image" src="https://github.com/user-attachments/assets/f7dc2cf1-38b9-4277-b5b5-a2957a6521d1">

Github is deprecation Node16, so the action needs to be updated

**Comment by zerj9** [comment]
> <img alt="image" width="1008" src="https://private-user-images.githubusercontent.com/14794642/348690154-f7dc2cf1-38b9-4277-b5b5-a2957a6521d1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQzMjUwNTksIm5iZiI6MTcyNDMyNDc1OSwicGF0aCI6Ii8xNDc5NDY0Mi8zNDg2OTAxNTQtZjdkYzJjZjEtMzhiOS00Mjc3LWI1YjUtYTI5NTdhNjUyMWQxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIyVDExMDU1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEyYzA5Y2FhMzQ0NDA3YmY4MGZkZmMyZTYwMjc1NTU0NmY5NjcxZWZmMjA3NjgwODk5ZWE0OWE4NDBlYjYyMGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5JzYJBpquHQ07vpGCtKJeDoNOe9N8PyVmv0nWlSx8y8">
> Github is deprecation Node16, so the action needs to be updated

Thanks @CMeldgaard! Updated to use Node20 and set newer default for the cargo lambda version.
